### ISSUE TITLE
连麦

### ISSUE THREAD

**Issue by zhaotoday** [AgoraIO-Community/Agora-Uniapp-SDK#1]
这个插件支持连麦吗？

**Comment by LichKing-2234** [comment]
支持，具体可以参考我们官网
https://docs.agora.io/cn/Video/API%20Reference/react_native/classes/rtcchannel.html#startchannelmediarelay

**Comment by zhaotoday** [comment]
感谢。

**Comment by zhaotoday** [comment]
@LichKing-2234 支持一对多视频吗？

**Comment by LichKing-2234** [comment]
除了自采集之类的都支持

**Comment by zhaotoday** [comment]
好的，谢谢。

**Comment by zhaotoday** [comment]
@LichKing-2234 
自采集是指推流组件用自己的，推流服务器用你们的？
自渲染是指拉流组件用自己的？

**Comment by LichKing-2234** [comment]
https://docs.agora.io/cn/Interactive%20Broadcast/custom_video_android?platform=Android#%E7%A4%BA%E4%BE%8B%E9%A1%B9%E7%9B%AE
