### ISSUE TITLE
必须要设置token吗？

### ISSUE THREAD

**Issue by xiaosatufu** [AgoraIO-Community/Agora-Uniapp-SDK#14]
必须要设置token吗？

**Comment by LichKing-2234** [comment]
不用的，如果官网控制台不开启，就传空即可

**Comment by LichKing-2234** [comment]
不过开启token是更安全的

**Comment by xiaosatufu** [comment]
为什么监听不到JoinChannelSuccess这个方法呢。。

**Comment by xiaosatufu** [comment]
声网后台水晶球也看不到通话状态

**Comment by xiaosatufu** [comment]
我甚至感觉joinChannel()这个方法没有调用成功，可是也没有任何报错返回

**Comment by xiaosatufu** [comment]
await this.engine &&
					this.engine.joinChannel(
						// config.token,
						'',
						this.channelId,
						null,
						this.uid
					);

**Comment by LichKing-2234** [comment]
官网默认的项目是开启token的，你可以新建一个不用鉴权的项目测试

**Comment by LichKing-2234** [comment]
对于开启token的项目可以使用官网控制台生成临时token测试

**Comment by xiaosatufu** [comment]
声网后台没有开启token

**Comment by xiaosatufu** [comment]
现在给我的感觉就是加入频道失败，可是又没有任何错误提示。

**Comment by xiaosatufu** [comment]
token  
beacb1469dc84b29aaf3a189b0d181ff at pages/Basic/JoinChannelVideo.nvue:59
![image](https://user-images.githubusercontent.com/12179854/123391673-d6e14980-d5ce-11eb-96be-4a9ad75b6c07.png)

**Comment by LichKing-2234** [comment]
api的调用是否成功和加入频道是否成功无关，可以监听Error和Warning事件，最好获取下SDK日志文件看下

**Comment by xiaosatufu** [comment]
如何监听error 和 warning  sdk日志在哪儿获取 ？

**Comment by xiaosatufu** [comment]
uid只能为number
