### ISSUE TITLE
自定义基座的问题

### ISSUE THREAD

**Issue by xiaosatufu** [AgoraIO-Community/Agora-Uniapp-SDK#16]
16:21:28.793 [JS Framework] 当前运行的基座不包含原生插件[Agora-RTC-ChannelModule]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座
16:21:28.825 [JS Framework] 当前运行的基座不包含原生插件[Agora-RTC-EngineModule]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座
-----------------------------------------------
后台已经绑定了此插件，自定义基座的完成，为什么感觉并没有加载到插件。
1.已经尝试过删除插件并且重新选择此插件加载并且重新自定义基座。
昨天都是正常的，不知道为何修改了一个接口以后，就不行了。
控制台打印感觉并没有运行到
this.engine = await RtcEngine.create(this.appId);
似乎到这句代码就停止了，不知道怎么办了。。

**Comment by xiaosatufu** [comment]
![image](https://user-images.githubusercontent.com/12179854/124092710-bcedae00-da89-11eb-8238-8c9d79e8fd01.png)
插件已经加载进去。

**Comment by LichKing-2234** [comment]
可以试试删除插件再绑定，然后再重新打自定义基座

**Comment by xiaosatufu** [comment]
已经试过了。重复试了几遍0 0

**Comment by xiaosatufu** [comment]
![image](https://user-images.githubusercontent.com/12179854/124093935-dd6a3800-da8a-11eb-94f4-f687afcf88b9.png)

不确定是不是和这个包名有关？购买是填写的包名为“uni.A572E99”
![image](https://user-images.githubusercontent.com/12179854/124093882-d511fd00-da8a-11eb-95e8-9998f0d080c3.png)

**Comment by xiaosatufu** [comment]
我删除了unpackage文件夹，删除了插件并且重新绑定，并且重新打包了自定义基座。
现在还是感觉没有运行到实例化那一步就直接结束了。。
打包的包名与购买的包名填写一致。

**Comment by LichKing-2234** [comment]
如果是基座有问题，控制台会提示的。如果是原生错误可以用adb logcat查看具体的错误。

**Comment by LichKing-2234** [comment]
还有我们昨天发布了新版本，你看下是不是js库版本不匹配

**Comment by LichKing-2234** [comment]
你依赖插件的时候有版本号么

**Comment by xiaosatufu** [comment]
没看到版本号

**Comment by LichKing-2234** [comment]
那有可能云打包会自动依赖最新版本，你可能要同步升级下对应的js库

**Comment by LichKing-2234** [comment]
或者用我们demo测试下

**Comment by xiaosatufu** [comment]
下载最新的示例包可以得到最新的版本库吗？

**Comment by LichKing-2234** [comment]
https://ext.dcloud.net.cn/plugin?id=3720

**Comment by xiaosatufu** [comment]
加载了最新的js库，现在正常了。
感谢您的耐心解答~
