### ISSUE TITLE
关于分辨率、帧率、码率的问题

### ISSUE THREAD

**Issue by xiaosatufu** [AgoraIO-Community/Agora-Uniapp-SDK#18]
您好，
根据声网关于分辨率的描述，如果没有设置的话，会根据当前网络状态自行选择最好的分辨率及帧率。
但是现在发现不管是在什么网络状态下，分辨率和帧率始终保持在640*360 帧率11左右 码率350小kbps
请问怎么才能自动的去获取最佳的方案呢？

**Comment by LichKing-2234** [comment]
这个可以联系我们的技术支持获取相关信息。
