### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by zhaotoday** [AgoraIO-Community/Agora-Uniapp-SDK#2]
1. 制作自定义基座并运行到手机或模拟器后，提示：
[JS Framework] 当前运行的基座不包含原生插件[Agora-RTC-ChannelModule]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座
[JS Framework] 当前运行的基座不包含原生插件[Agora-RTC-EngineModule]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座
但是，云打包没问题。
2. 这两个插件是一样的，为什么说
https://ext.dcloud.net.cn/plugin?id=3720
要配合
https://ext.dcloud.net.cn/plugin?id=3741
使用。

**Comment by LichKing-2234** [comment]
1、云打包没问题是指？自定义基座就是通过云打包生成的
2、只是README是一样的，
https://ext.dcloud.net.cn/plugin?id=3741（是JS包装，我们原生插件只导出了一个API）

具体看源码就知道了
https://github.com/AgoraIO-Community/Agora-Uniapp-SDK/blob/master/android/src/main/java/io/agora/rtc/uni/AgoraRtcEngineModule.kt#L29

**Comment by LichKing-2234** [comment]
1这个你有在manifest配置我们的原生插件么

**Comment by zhaotoday** [comment]
@LichKing-2234 我是下载 Agora-RTC_3.2.0_example 来用。已经配置 manifest，把 android_package_name 改成自己的。其他配置在 agora.config.js 里修改了。主要是调试时，提示这个错误，云打包不会。

**Comment by LichKing-2234** [comment]
调试也得基于自定义基座运行，直接跑是没有原生部分的

**Comment by LichKing-2234** [comment]
云打包的时候要打自定义基座

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
