### ISSUE TITLE
通过手机进入频道，但是有个电话进来了，接电话后还能听到频道内别人的声音，这个怎么怎么办？

### ISSUE THREAD

**Issue by meiqi1992** [AgoraIO-Community/Agora-Uniapp-SDK#21]
通过手机进入频道，但是有个电话进来了，把电话接起来后还能听到频道内别人的声音，这个怎么怎么办？但是频道内的其他人是听不到我说话

**Comment by LichKing-2234** [comment]
常规方案是监听系统事件，然后暂停音视频通话。不过不清楚uni-app有没有开放相关事件。
