### ISSUE TITLE
无法获取RtcEngine对象

### ISSUE THREAD

**Issue by hxx1995** [AgoraIO-Community/Agora-Uniapp-SDK#22]
调用 RtcEngine.create 方法的时候我APPID不论写得对不对他总是返回{"_listeners": {}} 这个问题可以解决一下吗

**Comment by LichKing-2234** [comment]
请问还有问题么

**Comment by OriharaIzaya7** [comment]
RtcEngine.create方法获取不到实例  返回的是rejected状态
