### ISSUE TITLE
实现一对一视频通话

### ISSUE THREAD

**Issue by zhaotoday** [AgoraIO-Community/Agora-Uniapp-SDK#3]
https://docs.agora.io/cn/Video/API%20Reference/react_native/classes/rtcchannel.html#rtcchannel.html#publish
一对一视频通话，是否需要两个频道？

**Comment by LichKing-2234** [comment]
不用，channel是用来同时加入多个频道的，正常直接用engine就好了

**Comment by LichKing-2234** [comment]
demo里有基本功能的展示，你可以参考下

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
