### ISSUE TITLE
安卓自定义基座打包报错

### ISSUE THREAD

**Issue by anchao-lu** [AgoraIO-Community/Agora-Uniapp-SDK#36]
<img width="1450" alt="WeChatdb469592782ba1c7671bc88f37c59019" src="https://user-images.githubusercontent.com/54097292/165492413-144d7398-759a-4236-9e2d-d58d27099fb7.png">

**Comment by LichKing-2234** [comment]
看起来是jitpack包管理工具的bug，后来都换成maven了，我们会尽快重发版本

**Comment by shaweigo** [comment]
请问，这个问题解决了吗？

**Comment by LichKing-2234** [comment]
最新版本已修复
