### ISSUE TITLE
joinChannel加入频道不报错也没走成功回调

### ISSUE THREAD

**Issue by ruanshipeng** [AgoraIO-Community/Agora-Uniapp-SDK#4]
用自定义基座运行项目，点击join channel调用joinChannel方法，没有走成功回调，也不报错

**Comment by LichKing-2234** [comment]
1、确认控制台有没有报错，如果是自定义基座问题，可以明显看出。 
2、默认我们控制台的应用是启用加密的，需要传token加入频道，请检查token有没有正确填写。（可以监听Warning和Error事件，通过查阅错误码可以自我排查不少问题） https://docs.agora.io/cn/Interactive%20Broadcast/faq/token_usage_generation_description

**Comment by ruanshipeng** [comment]
控制台没报错，token和appid也填了，Warning和Error也没响应

**Comment by LichKing-2234** [comment]
这不太可能，你跑的是我们的demo么

**Comment by hjp951212** [comment]
传的token是什么token呢？rtcToken还是userToken呢

**Comment by LichKing-2234** [comment]
@hjp951212 传入RtcToken，你说的usertoken是？

**Comment by hjp951212** [comment]
@LichKing-2234 那我传了rtcToken和appId以及channelId，观众身份为什么加入不进去呢，控制台也不报错

**Comment by LichKing-2234** [comment]
打包自定义基座正常？有用我们的demo测试么？

**Comment by hjp951212** [comment]
@LichKing-2234 打包基座正常，用的是插件市场你们提供的demo

**Comment by LichKing-2234** [comment]
那需要提供下logFile，你可以看下setLogFile的文档

**Comment by LichKing-2234** [comment]
你也可以监听下Error和Warn事件，看下错误码

**Comment by hjp951212** [comment]
@LichKing-2234 从哪里可以看到setLogFile呢

**Comment by hjp951212** [comment]
@LichKing-2234 
[agorasdk.log](https://github.com/AgoraIO-Community/Agora-Uniapp-SDK/files/6148420/agorasdk.log)

**Comment by LichKing-2234** [comment]
@hjp951212 日志没有看到joinChannel的调用，麻烦发下相关代码调用

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
