### ISSUE TITLE
有 java 版本的吗

### ISSUE THREAD

**Issue by Kerrui** [AgoraIO-Community/Agora-Uniapp-SDK#41]
有 java 版本的吗

**Comment by LichKing-2234** [comment]
没有，是有什么特殊需求要用java的么？

**Comment by Kerrui** [comment]
就是sdk升级到了 4.0 。但是这个插件没有更新到 4.0 版本。所以需要自己在当前版本基础上适配4.0，本人对kotlin不太熟悉。

**Comment by LichKing-2234** [comment]
如果自己开发的话，可以改成java，只不过kotlin和swift相近，Android iOS代码会看起来可读性会更高
