### ISSUE TITLE
可以适配 Android 12吗 

### ISSUE THREAD

**Issue by 99165655** [AgoraIO-Community/Agora-Uniapp-SDK#47]
可以适配 Android 12吗  否则谷歌商店 无法投放

**Comment by LichKing-2234** [comment]
请问是有什么错误信息么

**Comment by 99165655** [comment]
![Uploading dc5fcf4b1cfb7ff56b367c5529d240c.png…]()
谷歌 对 API 级别有限制

**Comment by LichKing-2234** [comment]
最新版本3.7.0.3已经更改，可以试试

**Comment by 99165655** [comment]
非常感謝 安卓確實沒問題了 但是 IOS 打包報錯

**Comment by LichKing-2234** [comment]
iOS也已经发了版本修复了
