### ISSUE TITLE
ios调用 RtcEngine.create 会闪退。

### ISSUE THREAD

**Issue by xiaonian0430** [AgoraIO-Community/Agora-Uniapp-SDK#5]
当调用 RtcEngine.create(“我的appID”);后，app 直接闪退了。

**Comment by LichKing-2234** [comment]
1、确保AppID正确
2、确保自定义基座加载成功

**Comment by LichKing-2234** [comment]
确认有授予麦克风摄像头权限

**Comment by xiaonian0430** [comment]
确认已授予麦克风摄像头权限，确定AppID是正确的，确定自定义基座加载成功。

使用你的demo可以正常，加入到我的项目， 调用 RtcEngine.create(“我的appID”);后，app 直接闪退了。

**Comment by xiaonian0430** [comment]
可以了，不会闪退了。谢谢。
