### ISSUE TITLE
Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6)

### ISSUE THREAD

**Issue by shaweigo** [AgoraIO-Community/Agora-Uniapp-SDK#50]
在进行自定义基座打包的时候，胡出现如下错误：

Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar

我看之前在4月份的时候，有人也遇到了这个问题，请问这个问题解决了吗？

**Comment by LichKing-2234** [comment]
最新版本已解决
