### ISSUE TITLE
iOS 集成离线打包模式报错

### ISSUE THREAD

**Issue by Mr-nan** [AgoraIO-Community/Agora-Uniapp-SDK#53]
<img width="405" alt="WeChat2357959fc4e2606425785e4a202937f0" src="https://user-images.githubusercontent.com/17428078/210296425-660a1ef3-528b-411d-bc3e-b27472df5e51.png">

**Comment by Mr-nan** [comment]
已解决

**Comment by LichKing-2234** [comment]
@Mr-nan 你好，可以分享下问题的原因和解决方案么?
