### ISSUE TITLE
云打包 上传应用市场后，提示ITMS-90426: Invalid Swift Support

### ISSUE THREAD

**Issue by xiaonian0430** [AgoraIO-Community/Agora-Uniapp-SDK#6]
云打包 上传应用市场后，提示ITMS-90426:  Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

**Comment by LichKing-2234** [comment]
这个建议和uni-app反馈下，是不是云打包服务器的xcode环境需要升级

**Comment by xiaonian0430** [comment]
应该跟uniapp 没有关系吧，不引入你的插件是正常的

**Comment by LichKing-2234** [comment]
因为插件用swift

**Comment by LichKing-2234** [comment]
你打包的是正式包么，可以参考这个文章看下
https://www.jianshu.com/p/c02e76c11fc8

**Comment by xiaonian0430** [comment]
是正式包

**Comment by xiaonian0430** [comment]
> 你打包的是正式包么，可以参考这个文章看下
> https://www.jianshu.com/p/c02e76c11fc8

我这边无法配置这些东西，我这边直接使用的是uniapp的云打包。

**Comment by LichKing-2234** [comment]
应该还是云打包对于swift的支持有问题，建议还是离线打包比较好。
https://ask.dcloud.net.cn/question/107442

**Comment by xiaonian0430** [comment]
无法离线打包。

**Comment by xiaonian0430** [comment]
麻烦你看一下你的插件，麻烦看一下，可以在插件中解决 这个问题吗？

**Comment by LichKing-2234** [comment]
建议uni-app官方群反馈下，我这边也会在他们群里反馈下

**Comment by LichKing-2234** [comment]
那些配置都是云打包服务器上的工程配置，如果不离线打包自定义，就完全依赖于uniapp的工程。插件本身已设置`"embedSwift": true,`，还是需要官方解决。

**Comment by xiaonian0430** [comment]
好的，我在uni-app官方群问

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
